name: Deploy Token API

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: [self-hosted, token]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set image tag
        id: vars
        run: echo "TAG=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Build Quarkus app
        working-directory: token
        run: ./mvnw clean package -DskipTests

      - name: Build image
        working-directory: token
        run: podman build --no-cache -t localhost/token-api:${TAG} .

      - name: Save image
        run: podman save localhost/token-api:${TAG} -o token-api.tar

      - name: Import into k3s
        run: sudo k3s ctr images import token-api.tar

      - name: Update deployment image
        run: |
          kubectl set image deployment/token-api \
          token-api=localhost/token-api:${TAG} -n cqrs-lab

      - name: Restart rollout
        run: kubectl rollout status deployment/token-api -n cqrs-lab
